# Generated by Django 3.1 on 2021-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=510)),
                ('area', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pgs',
            },
        ),
    ]
