# Generated by Django 3.1 on 2021-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgs',
            name='category',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
